version: '3.4'

services:
  renderquest:
    image: renderquest
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 3002:1337
    networks:
      - training_ad
    volumes:
      - /flag2.txt:/flag2.txt
networks:
  training_ad:
    external: true