version: '3.4'

services:
  webcop:
    container_name: web_cop_container
    image: webcop
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 3002:1337
    volumes:
      - /flag2.txt:/app/flag2.txt
