DROP TABLE IF EXISTS users;

CREATE TABLE users (
  usrname varchar UNIQUE NOT NULL,
  passwd varchar NOT NULL,
  token integer
);

INSERT INTO users (usrname, passwd) VALUES ('bkisc_admin', 'REDACTED');
INSERT INTO users (usrname, passwd, token) VALUES ('user_1', 'passwd_1', '1');
INSERT INTO users (usrname, passwd, token) VALUES ('user_3', 'passwd_3', '3');
INSERT INTO users (usrname, passwd, token) VALUES ('user_4', 'passwd_4', '4');
INSERT INTO users (usrname, passwd, token) VALUES ('user_5', 'passwd_5', '5');
INSERT INTO users (usrname, passwd, token) VALUES ('user_6', 'passwd_6', '6');
INSERT INTO users (usrname, passwd, token) VALUES ('user_7', 'passwd_7', '7');
INSERT INTO users (usrname, passwd, token) VALUES ('user_8', 'passwd_8', '8');
INSERT INTO users (usrname, passwd, token) VALUES ('user_9', 'passwd_9', '9');
INSERT INTO users (usrname, passwd, token) VALUES ('user_10', 'passwd_10', '10');
INSERT INTO users (usrname, passwd, token) VALUES ('user_11', 'passwd_11', '11');
INSERT INTO users (usrname, passwd, token) VALUES ('user_12', 'passwd_12', '12');
INSERT INTO users (usrname, passwd, token) VALUES ('user_13', 'passwd_13', '13');
INSERT INTO users (usrname, passwd, token) VALUES ('user_14', 'passwd_14', '14');
INSERT INTO users (usrname, passwd, token) VALUES ('user_15', 'passwd_15', '15');
INSERT INTO users (usrname, passwd, token) VALUES ('user_16', 'passwd_16', '16');
INSERT INTO users (usrname, passwd, token) VALUES ('user_17', 'passwd_17', '17');
INSERT INTO users (usrname, passwd, token) VALUES ('user_18', 'passwd_18', '18');
INSERT INTO users (usrname, passwd, token) VALUES ('user_19', 'passwd_19', '19');
INSERT INTO users (usrname, passwd, token) VALUES ('user_20', 'passwd_20', '20');
INSERT INTO users (usrname, passwd, token) VALUES ('user_21', 'passwd_21', '21');
INSERT INTO users (usrname, passwd, token) VALUES ('user_22', 'passwd_22', '22');
INSERT INTO users (usrname, passwd, token) VALUES ('user_23', 'passwd_23', '23');
INSERT INTO users (usrname, passwd, token) VALUES ('user_24', 'passwd_24', '24');
INSERT INTO users (usrname, passwd, token) VALUES ('user_25', 'passwd_25', '25');
INSERT INTO users (usrname, passwd, token) VALUES ('user_26', 'passwd_26', '26');
INSERT INTO users (usrname, passwd, token) VALUES ('user_27', 'passwd_27', '27');
INSERT INTO users (usrname, passwd, token) VALUES ('user_28', 'passwd_28', '28');
INSERT INTO users (usrname, passwd, token) VALUES ('user_29', 'passwd_29', '29');
INSERT INTO users (usrname, passwd, token) VALUES ('user_30', 'passwd_30', '30');
INSERT INTO users (usrname, passwd, token) VALUES ('user_31', 'passwd_31', '31');
INSERT INTO users (usrname, passwd, token) VALUES ('user_32', 'passwd_32', '32');
INSERT INTO users (usrname, passwd, token) VALUES ('user_33', 'passwd_33', '33');
INSERT INTO users (usrname, passwd, token) VALUES ('user_34', 'passwd_34', '34');
INSERT INTO users (usrname, passwd, token) VALUES ('user_35', 'passwd_35', '35');
INSERT INTO users (usrname, passwd, token) VALUES ('user_36', 'passwd_36', '36');
INSERT INTO users (usrname, passwd, token) VALUES ('user_37', 'passwd_37', '37');
INSERT INTO users (usrname, passwd, token) VALUES ('user_38', 'passwd_38', '38');
INSERT INTO users (usrname, passwd, token) VALUES ('user_39', 'passwd_39', '39');
INSERT INTO users (usrname, passwd, token) VALUES ('user_40', 'passwd_40', '40');
INSERT INTO users (usrname, passwd, token) VALUES ('user_41', 'passwd_41', '41');
INSERT INTO users (usrname, passwd, token) VALUES ('user_42', 'passwd_42', '42');
INSERT INTO users (usrname, passwd, token) VALUES ('user_43', 'passwd_43', '43');
INSERT INTO users (usrname, passwd, token) VALUES ('user_44', 'passwd_44', '44');
INSERT INTO users (usrname, passwd, token) VALUES ('user_45', 'passwd_45', '45');
INSERT INTO users (usrname, passwd, token) VALUES ('user_46', 'passwd_46', '46');
INSERT INTO users (usrname, passwd, token) VALUES ('user_47', 'passwd_47', '47');
INSERT INTO users (usrname, passwd, token) VALUES ('user_48', 'passwd_48', '48');
INSERT INTO users (usrname, passwd, token) VALUES ('user_49', 'passwd_49', '49');
INSERT INTO users (usrname, passwd, token) VALUES ('user_50', 'passwd_50', '50');
INSERT INTO users (usrname, passwd, token) VALUES ('user_51', 'passwd_51', '51');
INSERT INTO users (usrname, passwd, token) VALUES ('user_52', 'passwd_52', '52');
INSERT INTO users (usrname, passwd, token) VALUES ('user_53', 'passwd_53', '53');
INSERT INTO users (usrname, passwd, token) VALUES ('user_54', 'passwd_54', '54');
INSERT INTO users (usrname, passwd, token) VALUES ('user_55', 'passwd_55', '55');
INSERT INTO users (usrname, passwd, token) VALUES ('user_56', 'passwd_56', '56');
INSERT INTO users (usrname, passwd, token) VALUES ('user_57', 'passwd_57', '57');
INSERT INTO users (usrname, passwd, token) VALUES ('user_58', 'passwd_58', '58');
INSERT INTO users (usrname, passwd, token) VALUES ('user_59', 'passwd_59', '59');
INSERT INTO users (usrname, passwd, token) VALUES ('user_60', 'passwd_60', '60');
INSERT INTO users (usrname, passwd, token) VALUES ('user_61', 'passwd_61', '61');
INSERT INTO users (usrname, passwd, token) VALUES ('user_62', 'passwd_62', '62');
INSERT INTO users (usrname, passwd, token) VALUES ('user_63', 'passwd_63', '63');
INSERT INTO users (usrname, passwd, token) VALUES ('user_64', 'passwd_64', '64');
INSERT INTO users (usrname, passwd, token) VALUES ('user_65', 'passwd_65', '65');
INSERT INTO users (usrname, passwd, token) VALUES ('user_66', 'passwd_66', '66');
INSERT INTO users (usrname, passwd, token) VALUES ('user_67', 'passwd_67', '67');
INSERT INTO users (usrname, passwd, token) VALUES ('user_68', 'passwd_68', '68');
INSERT INTO users (usrname, passwd, token) VALUES ('user_69', 'passwd_69', '69');
INSERT INTO users (usrname, passwd, token) VALUES ('user_70', 'passwd_70', '70');
INSERT INTO users (usrname, passwd, token) VALUES ('user_71', 'passwd_71', '71');
INSERT INTO users (usrname, passwd, token) VALUES ('user_72', 'passwd_72', '72');
INSERT INTO users (usrname, passwd, token) VALUES ('user_73', 'passwd_73', '73');
INSERT INTO users (usrname, passwd, token) VALUES ('user_74', 'passwd_74', '74');
INSERT INTO users (usrname, passwd, token) VALUES ('user_75', 'passwd_75', '75');
INSERT INTO users (usrname, passwd, token) VALUES ('user_76', 'passwd_76', '76');
INSERT INTO users (usrname, passwd, token) VALUES ('user_77', 'passwd_77', '77');
INSERT INTO users (usrname, passwd, token) VALUES ('user_78', 'passwd_78', '78');
INSERT INTO users (usrname, passwd, token) VALUES ('user_79', 'passwd_79', '79');
INSERT INTO users (usrname, passwd, token) VALUES ('user_80', 'passwd_80', '80');
INSERT INTO users (usrname, passwd, token) VALUES ('user_81', 'passwd_81', '81');
INSERT INTO users (usrname, passwd, token) VALUES ('user_82', 'passwd_82', '82');
INSERT INTO users (usrname, passwd, token) VALUES ('user_83', 'passwd_83', '83');
INSERT INTO users (usrname, passwd, token) VALUES ('user_84', 'passwd_84', '84');
INSERT INTO users (usrname, passwd, token) VALUES ('user_85', 'passwd_85', '85');
INSERT INTO users (usrname, passwd, token) VALUES ('user_86', 'passwd_86', '86');
INSERT INTO users (usrname, passwd, token) VALUES ('user_87', 'passwd_87', '87');
INSERT INTO users (usrname, passwd, token) VALUES ('user_88', 'passwd_88', '88');
INSERT INTO users (usrname, passwd, token) VALUES ('user_89', 'passwd_89', '89');
INSERT INTO users (usrname, passwd, token) VALUES ('user_90', 'passwd_90', '90');
INSERT INTO users (usrname, passwd, token) VALUES ('user_91', 'passwd_91', '91');
INSERT INTO users (usrname, passwd, token) VALUES ('user_92', 'passwd_92', '92');
INSERT INTO users (usrname, passwd, token) VALUES ('user_93', 'passwd_93', '93');
INSERT INTO users (usrname, passwd, token) VALUES ('user_94', 'passwd_94', '94');
INSERT INTO users (usrname, passwd, token) VALUES ('user_95', 'passwd_95', '95');
INSERT INTO users (usrname, passwd, token) VALUES ('user_96', 'passwd_96', '96');
INSERT INTO users (usrname, passwd, token) VALUES ('user_97', 'passwd_97', '97');
INSERT INTO users (usrname, passwd, token) VALUES ('user_98', 'passwd_98', '98');
INSERT INTO users (usrname, passwd, token) VALUES ('user_99', 'passwd_99', '99');
INSERT INTO users (usrname, passwd, token) VALUES ('user_100', 'passwd_100', '100');


